// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9vQ-SaBxNkU_ziHqfeIO1Pzh3LIU09f8',
    appId: '1:251304641663:web:39ab02768e4f8abd282b4a',
    messagingSenderId: '251304641663',
    projectId: 'poster-test-project',
    authDomain: 'poster-test-project.firebaseapp.com',
    storageBucket: 'poster-test-project.appspot.com',
    databaseURL: 'https://poster-test-project-default-rtdb.europe-west1.firebasedatabase.app'
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_9z6B0HpEG4z4vD3qP1iEU5M0znJ3ebk',
    appId: '1:251304641663:android:3c387fbe12670c57282b4a',
    messagingSenderId: '251304641663',
    projectId: 'poster-test-project',
    storageBucket: 'poster-test-project.appspot.com',
    databaseURL: 'https://poster-test-project-default-rtdb.europe-west1.firebasedatabase.app'
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDz-InRsIWoZ3WkSFSmnLNqkdBJeMitMjU',
    appId: '1:251304641663:ios:740d00db13ce960b282b4a',
    messagingSenderId: '251304641663',
    projectId: 'poster-test-project',
    storageBucket: 'poster-test-project.appspot.com',
    iosBundleId: 'com.idteam.poster',
    databaseURL: 'https://poster-test-project-default-rtdb.europe-west1.firebasedatabase.app'
  );
}
